/** First-party assets generated by scripts/generate-seo-assets.mjs + hero photo. */
import { WARDOGS_TACTICAL, WARDOGS_OBJECTIVE } from './media'

export const WARDOGS_OG = '/og/wardogs-hacks.jpg'
export const WARDOGS_HERO = '/media/wardogs-product-hero.webp'
export const WARDOGS_COVER = '/media/wardogs-product-cover.webp'
export const WARDOGS_SOLDIER_HERO = '/media/wardogs-soldier-hero.jpg'

export type ImageSeoFields = {
  alt: string
  title: string
  caption: string
}

export const IMAGE_SEO: Record<
  string,
  ImageSeoFields & {
    heroAlt: string
    heroTitle: string
    heroCaption: string
  }
> = {
  wardogs: {
    alt: 'WARDOGS hacks product artwork for the tactical FPS',
    title: 'WARDOGS Hacks Product Details',
    caption: 'WARDOGS ESP, radar, aim assistance and Early Access compatibility',
    heroAlt: 'WARDOGS hacks features and PC compatibility',
    heroTitle: 'WARDOGS Hacks Features',
    heroCaption: 'Review WARDOGS ESP, radar, aim features and current status',
  },
}

type PageImage = ImageSeoFields & { src: string }

export const PAGE_IMAGES: Record<
  'home' | 'forums' | 'reviews' | 'faq' | 'support' | 'product',
  PageImage
> = {
  home: {
    src: WARDOGS_SOLDIER_HERO,
    alt: 'Tactical soldier overlooking a mountainous WARDOGS battlefield',
    title: 'WARDOGS Hacks for PC',
    caption: 'WARDOGS player ESP, radar and aim feature overview.',
  },
  forums: {
    src: WARDOGS_OBJECTIVE,
    alt: 'WARDOGS hacks setup and status guide artwork',
    title: 'WARDOGS Hacks Guides',
    caption: 'Setup, hotkey and compatibility guides for WARDOGS.',
  },
  reviews: {
    src: WARDOGS_TACTICAL,
    alt: 'WARDOGS hacks product evaluation artwork',
    title: 'WARDOGS Hacks Reviews',
    caption: 'Feature and compatibility feedback for the new WARDOGS release.',
  },
  faq: {
    src: WARDOGS_OBJECTIVE,
    alt: 'WARDOGS hacks frequently asked questions artwork',
    title: 'WARDOGS Hacks FAQ',
    caption: 'Compatibility, feature and setup answers for WARDOGS.',
  },
  support: {
    src: WARDOGS_TACTICAL,
    alt: 'WARDOGS hacks support artwork',
    title: 'WARDOGS Hacks Support',
    caption: 'Delivery, loader and setup support for WARDOGS.',
  },
  product: {
    src: WARDOGS_OBJECTIVE,
    alt: 'WARDOGS ESP radar and aim product artwork',
    title: 'WARDOGS Hacks Features',
    caption: 'Product details for WARDOGS ESP, radar and aim assistance.',
  },
}

export function getGameImage(_slug: string): string {
  return WARDOGS_COVER
}

export function getProductHeroImage(slug: string): string {
  return slug === 'wardogs' ? WARDOGS_HERO : getGameImage(slug)
}

export function getOgImage(path?: string): string {
  if (!path || path === '/') return PAGE_IMAGES.home.src
  if (path === '/wardogs-hacks') return PAGE_IMAGES.product.src
  if (path === '/forums') return PAGE_IMAGES.forums.src
  if (path === '/reviews') return PAGE_IMAGES.reviews.src
  if (path === '/faq') return PAGE_IMAGES.faq.src
  if (path === '/support') return PAGE_IMAGES.support.src
  return WARDOGS_OG
}

export function getPageImage(key: keyof typeof PAGE_IMAGES) {
  return PAGE_IMAGES[key]
}

export function getImageAlt(
  slug: string,
  name: string,
  variant: 'catalog' | 'product' = 'catalog',
): string {
  const seo = IMAGE_SEO[slug]
  if (seo) return variant === 'product' ? seo.heroAlt : seo.alt
  return variant === 'product' ? `${name} product details` : `${name} product artwork`
}

export function getImageTitle(
  slug: string,
  name: string,
  variant: 'catalog' | 'product' = 'catalog',
): string {
  const seo = IMAGE_SEO[slug]
  if (seo) return variant === 'product' ? seo.heroTitle : seo.title
  return `${name} product`
}
